name: CI/CD → ECR & ECS

on:
  push:
    branches:
      - main
    paths:
      - 'services/products/**'
      - 'services/sales/**'
      - 'services/sellers/**'

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_PREFIX: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
  ECS_CLUSTER: modernizacion-cluster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [products, sales, sellers]
    defaults:
      run:
        working-directory: services/${{ matrix.service }}

    steps:
      - name: Checkout code (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch main branch for diff
        run: git fetch --no-tags origin main

      - name: Detect changes in ${{ matrix.service }}
        id: changed
        run: |
          echo "Comparing origin/main → $GITHUB_SHA"
          if git diff --name-only origin/main $GITHUB_SHA \
               | grep -q "^services/${{ matrix.service }}/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip build & deploy if no changes
        if: steps.changed.outputs.changed == 'false'
        run: echo "No changes in services/${{ matrix.service }}; skipping."

      - name: Configure AWS credentials
        if: steps.changed.outputs.changed == 'true'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions

      - name: Log in to Amazon ECR
        if: steps.changed.outputs.changed == 'true'
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker image
        if: steps.changed.outputs.changed == 'true'
        run: |
          IMAGE_URI=${ECR_PREFIX}/${{ matrix.service }}:${GITHUB_SHA}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          docker tag $IMAGE_URI ${ECR_PREFIX}/${{ matrix.service }}:latest
          docker push ${ECR_PREFIX}/${{ matrix.service }}:latest

      - name: Force new ECS deployment
        if: steps.changed.outputs.changed == 'true'
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service ${{ matrix.service }} \
            --force-new-deployment
