name: CI → ECR

on:
  push:
    branches:
      - main
    paths:
      - 'backend/services/**'

env:
  AWS_REGION:    ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [products, sales, sellers]

    defaults:
      run:
        working-directory: backend/services/${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch full history for diff
        run: git fetch --no-tags origin main

      - name: Detect changes in ${{ matrix.service }}
        id: changed
        run: |
          echo "Comparing ${{ github.event.before }} → ${{ github.sha }}"
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
               | grep -q "^backend/services/${{ matrix.service }}/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip build if no changes
        if: steps.changed.outputs.changed == 'false'
        run: echo "No changes in ${{ matrix.service }}, skipping."

      - name: Configure AWS credentials
        if: steps.changed.outputs.changed == 'true'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        if: steps.changed.outputs.changed == 'true'
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag & push Docker image
        if: steps.changed.outputs.changed == 'true'
        run: |
          ECR_PREFIX=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          IMAGE_SHA=$ECR_PREFIX/${{ matrix.service }}:${GITHUB_SHA}
          IMAGE_LATEST=$ECR_PREFIX/${{ matrix.service }}:latest

          docker build -t $IMAGE_SHA .
          docker push $IMAGE_SHA

          docker tag $IMAGE_SHA $IMAGE_LATEST
          docker push $IMAGE_LATEST

      - name: Set output.tf image URIs
        if: steps.changed.outputs.changed == 'true'
        id: image
        run: |
          ECR_PREFIX=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          echo "::set-output name=sha_image::${ECR_PREFIX}/${{ matrix.service }}:${GITHUB_SHA}"
          echo "::set-output name=latest_image::${ECR_PREFIX}/${{ matrix.service }}:latest"
